### ISSUE TITLE
Make "development" master branch 

### ISSUE THREAD

**Issue by tiferrei** [Abutler101/Arduino-Quadcopter#1]
Alex, please change the `master` branch to `development`, so that I can delete `master` whilst we don't have a release version.

Tiago

**Comment by Abutler101** [comment]
Will do, not sure how to remove a branch?



Sent from Samsung Mobile on O2


-------- Original message --------

**Comment by tiferrei** [comment]
Don't worry, just change the master branch to development on settings > branches and then I'll delete the master

**Comment by Abutler101** [comment]
All done



Sent from Samsung Mobile on O2


-------- Original message --------

**Comment by tiferrei** [comment]
Cool, merged the `Dev` into `development` and deleted others, remember to now change to the `development` branch.

Closing issue.
